MyKanban/MyKanbanCore/Models/Board.cs
using MyKanbanCore.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyKanbanCore.Models
{
    public class Board
    {
        [Key]
        public int BoardId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Column> Columns { get; set; }
    }
}

MyKanban/MyKanbanCore/Controllers/BoardsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyKanbanCore.Business_logic;
using MyKanbanCore.Data;
using MyKanbanCore.Models;

namespace MyKanbanCore.Controllers
{
    public class BoardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BoardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Boards
        public async Task<IActionResult> Index()
        {
            return View(await _context.Board.ToListAsync());
        }

        // GET: Boards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board
                .Include(s => s.Columns).ThenInclude(s => s.Items)
                .FirstOrDefaultAsync(m => m.BoardId == id);
            if (board == null)
            {
                return NotFound();
            }

            ViewBag.Boards = await _context.Board.ToListAsync();
            return View(board);
        }

        // GET: Boards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoardId,Name,Description")] Board board)
        {
            if (ModelState.IsValid)
            {
                new BoardHandler(_context).init(board);
                _context.Add(board);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Boards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board.FindAsync(id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }

        // POST: Boards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoardId,Name,Description")] Board board)
        {
            if (id != board.BoardId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(board);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoardExists(board.BoardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Boards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Board
                .FirstOrDefaultAsync(m => m.BoardId == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // POST: Boards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var board = await _context.Board.FindAsync(id);
            _context.Board.Remove(board);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoardExists(int id)
        {
            return _context.Board.Any(e => e.BoardId == id);
        }
    }
}

MyKanban/MyKanbanCore/Controllers/ColumnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyKanbanCore.Data;
using MyKanbanCore.Models;

namespace MyKanbanCore.Controllers
{
    public class ColumnsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ColumnsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Columns
        public async Task<IActionResult> Index(int? id)
        {
            IQueryable<Column> applicationDbContext = _context.Column.Include(c => c.Board);

            if (id != null && id > 0)
            {
                applicationDbContext = applicationDbContext.Where(s => s.BoardId == id);
                ViewBag.BoardId = id;
            }
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Columns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var column = await _context.Column
                .Include(c => c.Board)
                .FirstOrDefaultAsync(m => m.ColumnId == id);
            if (column == null)
            {
                return NotFound();
            }

            return View(column);
        }

        // GET: Columns/Create
        public IActionResult Create(int? id)
        {
            Column newColumn = new Column();

            if (id != null && id > 0)
            {
                var board = _context.Board.Find(id);

                newColumn.BoardId = id;
                newColumn.Board = board;
            }

            return View(newColumn);
        }

        // POST: Columns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ColumnId,Description,BoardId")] Column column)
        {
            if (ModelState.IsValid)
            {
                _context.Add(column);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = column.BoardId });
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", column.BoardId);
            return View(column);
        }

        // GET: Columns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var column = await _context.Column.FindAsync(id);
            if (column == null)
            {
                return NotFound();
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", column.BoardId);
            return View(column);
        }

        // POST: Columns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ColumnId,Description,BoardId")] Column column)
        {
            if (id != column.ColumnId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(column);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ColumnExists(column.ColumnId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", column.BoardId);
            return View(column);
        }

        // GET: Columns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var column = await _context.Column
                .Include(c => c.Board)
                .FirstOrDefaultAsync(m => m.ColumnId == id);
            if (column == null)
            {
                return NotFound();
            }

            return View(column);
        }

        // POST: Columns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var column = await _context.Column.FindAsync(id);
            _context.Column.Remove(column);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ColumnExists(int id)
        {
            return _context.Column.Any(e => e.ColumnId == id);
        }
    }
}

MyKanban/MyKanbanCore/Controllers/ItemsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyKanbanCore.Models;
using MyKanbanCore.Data;
using MyKanbanCore.Business_logic;

namespace MyKanbanCore.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Item.Include(i => i.Board).Include(i => i.Column);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.Board)
                .Include(i => i.Column)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create(int? id)
        {
            var newItem = new Item()
            {
                DateCreated = DateTime.Today
            };

            var column = _context.Column.Include(s => s.Board).Where(s => s.ColumnId == id).FirstOrDefault();
            if (column != null)
            {
                newItem.ColumnId = column.ColumnId;
                newItem.Column = column;
                newItem.BoardId = column.BoardId;
                newItem.Board = column.Board;
            }

            //ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name");
            //ViewData["ColumnId"] = new SelectList(_context.Column, "ColumnId", "Description");
            return View(newItem);
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,DateCreated,Description,ColumnId,BoardId,Critical")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                new ItemsHandler(_context).setPositionForNew(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), "Boards", new { id = item.BoardId });
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", item.BoardId);
            ViewData["ColumnId"] = new SelectList(_context.Column, "ColumnId", "Description", item.ColumnId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", item.BoardId);
            ViewData["ColumnId"] = new SelectList(_context.Column, "ColumnId", "Description", item.ColumnId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,DateCreated,Description,ColumnId,BoardId,Critical")] Item item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoardId"] = new SelectList(_context.Board, "BoardId", "Name", item.BoardId);
            ViewData["ColumnId"] = new SelectList(_context.Column, "ColumnId", "Description", item.ColumnId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.Board)
                .Include(i => i.Column)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.FindAsync(id);
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ItemId == id);
        }
    }
}

MyKanban/MyKanbanCore/Views/Boards/Create.cshtml
@model MyKanbanCore.Models.Board

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyKanban/MyKanbanCore/Views/Boards/Delete.cshtml
@model MyKanbanCore.Models.Board

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BoardId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyKanban/MyKanbanCore/Views/Boards/Details.cshtml
@model MyKanbanCore.Models.Board

@{
    ViewData["Title"] = "Details";
}

<div class="sidenav">
    @foreach (var item in ViewBag.Boards)
    {
        <a asp-action="Details" asp-route-id="@item.BoardId">@item.Name</a>
    }
    <hr />
    <a asp-action="Create">Create New</a>
</div>

<div class="main">
    <h2 class="d-inline">@Html.DisplayFor(model => model.Name)</h2>
    <a class="d-inline" asp-action="Index" asp-controller="Columns" asp-route-id="@Model.BoardId"> (Manage columns)</a>
    <hr />

    <div class="row">
        @foreach (Column column in Model.Columns)
        {
            <div class="col">
                <h5 class="d-inline">@column.Description</h5>
                <a class="d-inline" asp-action="Create" asp-controller="Items" asp-route-id="@column.ColumnId" style="visibility: hidden"> (create item)</a>
                <ul id="@string.Format("sortable{0}", column.ColumnId)" class="connectedSortable kanbanColumn" data-columnId="@column.ColumnId">
                    @foreach (Item item in column.Items.OrderBy(s => s.Position))
                    {
                        <li class="kanbanItem" data-itemId="@item.ItemId">@item.Description</li>
                    }
                </ul>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="~/js/boarditems.js"></script>
}

MyKanban/MyKanbanCore/Views/Boards/Edit.cshtml
@model MyKanbanCore.Models.Board

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BoardId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyKanban/MyKanbanCore/Views/Boards/Index.cshtml
@model IEnumerable<MyKanbanCore.Models.Board>

@{
    ViewData["Title"] = "Index";
}

<div class="sidenav">
    @foreach (var item in Model)
    {
        <a asp-action="Details" asp-route-id="@item.BoardId">@item.Name</a>
    }
    <hr />
    <a asp-action="Create">Create New</a>
</div>

<div class="main">
    <h2>Please select a board</h2>
    <p><i class="fa fa-arrow-left"></i> Select or create a board to begin...</p>
</div>