MyKanban/MyKanban/Controllers/KanbanBoardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyKanban.Models;

namespace MyKanban.Controllers
{
    public class KanbanBoardsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Items(int? id)
        {
            SplitKanbanListItemsByColumn listHelper = new SplitKanbanListItemsByColumn(id);
            
            ViewBag.Todo = listHelper.toDo;
            ViewBag.InProcess = listHelper.inProcess;
            ViewBag.Done = listHelper.done;
            ViewBag.TodoCounter = listHelper.toDo.Count();
            ViewBag.InProcessCounter = listHelper.inProcess.Count();
            ViewBag.DoneCounter = listHelper.done.Count();
            ViewBag.BoardName = listHelper.boardName;

            return View();
        }

        // GET: KanbanBoards
        public ActionResult Index()
        {
            return View(db.KanbanBoards.ToList());
        }

        // GET: KanbanBoards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KanbanBoards/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.KanbanBoards.Add(kanbanBoard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kanbanBoard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            db.KanbanBoards.Remove(kanbanBoard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyKanban/MyKanban/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Kanban</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Kanban", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Boards", "Index", "KanbanBoards")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>