MyKanban/MyKanban/Models/KanbanBoard.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyKanban.Models
{
    public class KanbanBoard
    {
        public int ID { get; set; }

        [Display(Name = "Name")]
        [Required]
        public string Description { get; set; }

        public virtual ICollection<KanbanItem> Items { get; set; }
    }
}

MyKanban/MyKanban/Controllers/KanbanBoardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyKanban.Models;

namespace MyKanban.Controllers
{
    public class KanbanBoardsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Items(int? id)
        {
            SplitKanbanListItemsByColumn listHelper = new SplitKanbanListItemsByColumn(id);
            
            ViewBag.Todo = listHelper.toDo;
            ViewBag.InProcess = listHelper.inProcess;
            ViewBag.Done = listHelper.done;
            ViewBag.TodoCounter = listHelper.toDo.Count();
            ViewBag.InProcessCounter = listHelper.inProcess.Count();
            ViewBag.DoneCounter = listHelper.done.Count();
            ViewBag.BoardName = listHelper.boardName;

            return View();
        }

        // GET: KanbanBoards
        public ActionResult Index()
        {
            return View(db.KanbanBoards.ToList());
        }

        // GET: KanbanBoards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KanbanBoards/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.KanbanBoards.Add(kanbanBoard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description")] KanbanBoard kanbanBoard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kanbanBoard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kanbanBoard);
        }

        // GET: KanbanBoards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            if (kanbanBoard == null)
            {
                return HttpNotFound();
            }
            return View(kanbanBoard);
        }

        // POST: KanbanBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KanbanBoard kanbanBoard = db.KanbanBoards.Find(id);
            db.KanbanBoards.Remove(kanbanBoard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyKanban/MyKanban/Controllers/KanbanItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyKanban.Models;

namespace MyKanban.Controllers
{
    public class KanbanItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: KanbanItems
        public ActionResult Index()
        {
            var kanbanItems = db.KanbanItems.Include(k => k.Board);
            return View(kanbanItems.ToList());
        }

        // GET: KanbanItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanItem kanbanItem = db.KanbanItems.Find(id);
            if (kanbanItem == null)
            {
                return HttpNotFound();
            }
            return View(kanbanItem);
        }

        // GET: KanbanItems/Create
        public ActionResult Create()
        {
            ViewBag.BoardID = new SelectList(db.KanbanBoards, "ID", "Description");
            return View();
        }

        // POST: KanbanItems/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,DateCreated,ColumnID,Critical,BoardID")] KanbanItem kanbanItem)
        {
            var dateTimeNow = DateTime.Now;
            kanbanItem.DateCreated = dateTimeNow.Date;

            if (ModelState.IsValid)
            {
                db.KanbanItems.Add(kanbanItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BoardID = new SelectList(db.KanbanBoards, "ID", "Description", kanbanItem.BoardID);
            return View(kanbanItem);
        }

        // GET: KanbanItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanItem kanbanItem = db.KanbanItems.Find(id);
            if (kanbanItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoardID = new SelectList(db.KanbanBoards, "ID", "Description", kanbanItem.BoardID);
            return View(kanbanItem);
        }

        // POST: KanbanItems/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,DateCreated,ColumnID,Critical,BoardID")] KanbanItem kanbanItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kanbanItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BoardID = new SelectList(db.KanbanBoards, "ID", "Description", kanbanItem.BoardID);
            return View(kanbanItem);
        }

        // GET: KanbanItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KanbanItem kanbanItem = db.KanbanItems.Find(id);
            if (kanbanItem == null)
            {
                return HttpNotFound();
            }
            return View(kanbanItem);
        }

        // POST: KanbanItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KanbanItem kanbanItem = db.KanbanItems.Find(id);
            db.KanbanItems.Remove(kanbanItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyKanban/MyKanban/Views/KanbanBoards/Create.cshtml
@model MyKanban.Models.KanbanBoard

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KanbanBoard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyKanban/MyKanban/Views/KanbanBoards/Delete.cshtml
@model MyKanban.Models.KanbanBoard

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KanbanBoard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyKanban/MyKanban/Views/KanbanBoards/Details.cshtml
@model MyKanban.Models.KanbanBoard

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>KanbanBoard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyKanban/MyKanban/Views/KanbanBoards/Edit.cshtml
@model MyKanban.Models.KanbanBoard

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KanbanBoard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyKanban/MyKanban/Views/KanbanBoards/Index.cshtml
@model IEnumerable<MyKanban.Models.KanbanBoard>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Items", "Items", new { id = item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MyKanban/MyKanban/Views/KanbanBoards/Items.cshtml
@model IEnumerable<MyKanban.Models.KanbanItem>

@{
    ViewBag.Title = "Items";
}

<h2>Items</h2>

<p>
    @Html.ActionLink("Create New", "Create", "KanbanItems")
</p>
<div class="row">
    <div class="col-sm-4">
        <div class="panel">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4 class="dropelement" draggable="true">To do (@ViewBag.TodoCounter)</h4>
            </div>
            <!-- Table -->
            <table class="table">
                @foreach (var item in (IEnumerable<MyKanban.Models.KanbanItem>)ViewBag.Todo)
                {
                    <tr>
                        <td>
                            <a href="/KanbanItems/Details/@item.ID" class="dragelement" draggable="true">
                                @if (item.Critical == true)
                                {
                                    <b>@item.shortDescription()</b>

                                }
                                else
                                {
                                    @item.shortDescription()
                                }
                                <br />
                                <small> (@item.daysElapsed())</small>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="panel">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4>In process (@ViewBag.InProcessCounter)</h4>
            </div>
            <!-- Table -->
            <table class="table">
                @foreach (var item in (IEnumerable<MyKanban.Models.KanbanItem>)ViewBag.InProcess)
                {
                    <tr>
                        <td>
                            <a href="/KanbanItems/Details/@item.ID">
                                @if (item.Critical == true)
                                {
                                    <b>@item.shortDescription()</b>

                                }
                                else
                                {
                                    @item.shortDescription()
                                }
                                <br />
                                <small> (@item.daysElapsed())</small>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <div class="col-sm-4" style="padding-right:0;">
        <div class="panel">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4>Done (@ViewBag.DoneCounter)</h4>
            </div>
            <!-- Table -->
            <table class="table">
                @foreach (var item in (IEnumerable<MyKanban.Models.KanbanItem>)ViewBag.Done)
                {
                    <tr>
                        <td>
                            <a href="/KanbanItems/Details/@item.ID">
                                @if (item.Critical == true)
                                {
                                    <b>@item.shortDescription()</b>

                                }
                                else
                                {
                                    @item.shortDescription()
                                }
                                <br />
                                <small> (@item.daysElapsed())</small>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>